$OAPI_contents = Get-Content "..\include\OrbiterAPI.h"

$headerContents = ""
$cpp = @"
#include "Hooks.h"
#include "detours.h"
#include <Windows.h>
"@
$installHooks = ""
$detachHooks = ""
$functionPointers = ""
$functions = ""

foreach($line in $OAPI_contents)
{
	#Make pointers adjacent to make stripping info out easier
	$line = $line -replace " \*", "* "
	$line = $line -replace " &", "& " 
	#Remove default params
	$line = $line -replace " = \S+",""
	if ($line -match "OAPIFUNC (?<returnType>.+) oapi(?<funcName>\w+) \((?<args>.+)\);")
	{
		#echo $matches[0]
		$returnType = $matches['returnType']
		$returnType = $returnType.trim()
		$funcName = $matches['funcName']
		$args = $matches['args']
		$arg_array = $args.Split(',')
		$argType_array = @()
		$argName_array = @()
		foreach($arg in $arg_array)
		{
			#trim whitespace
			$arg = $arg.trim()
			$arg -match "\s*(?<argType>.*) (?<argName>\S*)\s*"
			$argType_array += ($matches['argType'])
			$argName_array += ($matches['argName'])
		}
		#now we have all the info we need
		#write the typedef and the function declaration
		$header_value = "typedef OAPIFUNC $returnType (*OSDK_$funcName)(" + ($argType_array -join ',') + ');' +
			"`r`n" + "$returnType  My$funcName(" + ($arg_array -join ',') + ");`r`n"
		$headerContents += $header_value
		$functionPointers += "OSDK_$funcName $funcName = oapi$funcName;`r`n"
		$installHooks += "	DetourAttach(&(PVOID&)$funcName, My$funcName);`r`n"
		$detachHooks += "	DetourDetach(&(PVOID&)$funcName, My$funcName);`r`n"
		$functions += 
@"
$returnType  My$funcName($($arg_array -join ','))
	{
		Log::increaseIndent();
		Log::writeToLog("oapi$($funcName):",$($argName_array -join ' , ",", '));
		$funcName($($argName_array -join ','));
		Log::writeToLog("\n");
		Log::decreaseIndent();
	}
	
"@
	}
}
$header = @"
//This file is autogenerated by writeHooks.ps1
//Do not edit or add to source control!
//Instead edit writeHooks and regenerate
#ifndef CATCH_CTD_HOOKS
#define CATCH_CTD_HOOKS
#include "Orbitersdk.h"

bool InstallGlobalOAPIHooks();
bool DetachGlobalOAPIHooks();

$headerContents

#endif
"@

$cpp = @"
//This file is autogenerated by writeHooks.ps1
//Do not edit or add to source control!
//Instead edit writeHooks and regenerate
#include "Hooks.h"
#include <Windows.h>
#include "detours.h"

$functionPointers

bool InstallGlobalOAPIHooks()
{
	DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread());
	$installHooks
	return DetourTransactionCommit();
}

bool DetachGlobalOAPIHooks()
{
	DetourTransactionBegin();
    DetourUpdateThread(GetCurrentThread());
	$detachHooks
	return DetourTransactionCommit();
}

$functions

"@
$header | out-file Hooks.h -encoding ASCII
$cpp | out-file Hooks.cpp -encoding ASCII